return
{
	"_preload.lua",
	"androidproj.lua",
	"androidproj_build_xml.lua",
	"androidproj_manifest_xml.lua",
	"androidproj_project_properties.lua",
	"sln_customizations.lua",
	"vcxproj_customizations.lua",
	"vstudio_customizations.lua",
}